# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/gts2-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_apsta.bin_4358:system/etc/wifi/bcmdhd_apsta.bin_4358 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_apsta.bin_a1:system/etc/wifi/bcmdhd_apsta.bin_a1 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_ibss.bin:system/etc/wifi/bcmdhd_ibss.bin \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_ibss.bin_4358:system/etc/wifi/bcmdhd_ibss.bin_4358 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_ibss.bin_a1:system/etc/wifi/bcmdhd_ibss.bin_a1 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_mfg.bin_4358:system/etc/wifi/bcmdhd_mfg.bin_4358 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_mfg.bin_a1:system/etc/wifi/bcmdhd_mfg.bin_a1 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_sta.bin_4358:system/etc/wifi/bcmdhd_sta.bin_4358 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_sta.bin_a1:system/etc/wifi/bcmdhd_sta.bin_a1 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/cred.conf:system/etc/wifi/cred.conf \
    vendor/samsung/gts2-common/proprietary/vendor/firmware/hevc_fw.bin:system/vendor/firmware/hevc_fw.bin \
    vendor/samsung/gts2-common/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/gts2-common/proprietary/vendor/firmware/fimc_is_fw2_4h5.bin:system/vendor/firmware/fimc_is_fw2_4h5.bin \
    vendor/samsung/gts2-common/proprietary/vendor/firmware/seiren_fw_dram.bin:system/vendor/firmware/seiren_fw_dram.bin \
    vendor/samsung/gts2-common/proprietary/vendor/firmware/seiren_fw_sram.bin:system/vendor/firmware/seiren_fw_sram.bin \
    vendor/samsung/gts2-common/proprietary/vendor/firmware/bcm4358A3_V0083.0139.hcd:system/vendor/firmware/bcm4358A3_V0083.0139.hcd \
    vendor/samsung/gts2-common/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/gts2-common/proprietary/lib/hw/camera.universal5433.so:system/lib/hw/camera.universal5433.so \
    vendor/samsung/gts2-common/proprietary/lib/libexynoscamera.so:system/lib/libexynoscamera.so \
    vendor/samsung/gts2-common/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
    vendor/samsung/gts2-common/proprietary/lib/libsensorlistener.so:system/lib/libsensorlistener.so \
    vendor/samsung/gts2-common/proprietary/lib/libvdis.so:system/lib/libvdis.so \
    vendor/samsung/gts2-common/proprietary/vendor/firmware/setfile_4h5.bin:system/vendor/firmware/setfile_4h5.bin \
    vendor/samsung/gts2-common/proprietary/vendor/firmware/setfile_6b2.bin:system/vendor/firmware/setfile_6b2.bin \
    vendor/samsung/gts2-common/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/samsung/gts2-common/proprietary/lib/hw/gralloc.exynos5.so:system/lib/hw/gralloc.exynos5.so \
    vendor/samsung/gts2-common/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/samsung/gts2-common/proprietary/vendor/lib/libOpenCv.so:system/vendor/lib/libOpenCv.so \
    vendor/samsung/gts2-common/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/samsung/gts2-common/proprietary/lib/libion_exynos.so:system/lib/libion_exynos.so \
    vendor/samsung/gts2-common/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/gts2-common/proprietary/lib/libyasalgo.so:system/lib/libyasalgo.so \
    vendor/samsung/gts2-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/gts2-common/proprietary/bin/cs:system/bin/cs \
    vendor/samsung/gts2-common/proprietary/lib/libbauthserver.so:system/lib/libbauthserver.so \
    vendor/samsung/gts2-common/proprietary/lib/libbauthtzcommon.so:system/lib/libbauthtzcommon.so \
    vendor/samsung/gts2-common/proprietary/lib/libsynaFpSensorTestNwd.so:system/lib/libsynaFpSensorTestNwd.so \
    vendor/samsung/gts2-common/proprietary/lib/libegis_fp_normal_sensor_test.so:system/lib/libegis_fp_normal_sensor_test.so \
    vendor/samsung/gts2-common/proprietary/vendor/lib/libMcClient.so:system/vendor/lib/libMcClient.so \
    vendor/samsung/gts2-common/proprietary/vendor/lib/libMcRegistry.so:system/vendor/lib/libMcRegistry.so \
    vendor/samsung/gts2-common/proprietary/bin/mcDriverDaemon:system/bin/mcDriverDaemon \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_apsta.bin_4356_a2:system/etc/wifi/bcmdhd_apsta.bin_4356_a2 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_apsta.bin_4358_a1:system/etc/wifi/bcmdhd_apsta.bin_4358_a1 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_apsta.bin_a1:system/etc/wifi/bcmdhd_apsta.bin_a1 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_ibss.bin:system/etc/wifi/bcmdhd_ibss.bin \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_ibss.bin_4356_a2:system/etc/wifi/bcmdhd_ibss.bin_4356_a2 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_ibss.bin_4358_a1:system/etc/wifi/bcmdhd_ibss.bin_4358_a1 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_ibss.bin_a1:system/etc/wifi/bcmdhd_ibss.bin_a1 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_mfg.bin_4356_a2:system/etc/wifi/bcmdhd_mfg.bin_4356_a2 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_mfg.bin_4358_a1:system/etc/wifi/bcmdhd_mfg.bin_4358_a1 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_mfg.bin_a1:system/etc/wifi/bcmdhd_mfg.bin_a1 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_sta.bin_4356_a2:system/etc/wifi/bcmdhd_sta.bin_4356_a2 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_sta.bin_4358_a1:system/etc/wifi/bcmdhd_sta.bin_4358_a1 \
    vendor/samsung/gts2-common/proprietary/etc/wifi/bcmdhd_sta.bin_a1:system/etc/wifi/bcmdhd_sta.bin_a1 \
    vendor/samsung/gts2-common/proprietary/lib/libfloatingfeature.so:system/lib/libfloatingfeature.so \
    vendor/samsung/gts2-common/proprietary/app/FFFFFFFF000000000000000000000001.drbin:system/app/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/02010000080300030000000000000000.tlbin:system/app/mcRegistry/02010000080300030000000000000000.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000a.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000a.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000b.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000b.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000e.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000e.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffff00000000000000000000000f.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000f.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffff00000000000000000000003e.tlbin:system/app/mcRegistry/ffffffff00000000000000000000003e.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:system/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffff000000000000000000000011.tlbin:system/app/mcRegistry/ffffffff000000000000000000000011.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffff000000000000000000000012.tlbin:system/app/mcRegistry/ffffffff000000000000000000000012.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffff000000000000000000000013.tlbin:system/app/mcRegistry/ffffffff000000000000000000000013.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffff000000000000000000000016.tlbin:system/app/mcRegistry/ffffffff000000000000000000000016.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffff000000000000000000000017.tlbin:system/app/mcRegistry/ffffffff000000000000000000000017.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffff000000000000000000000019.tlbin:system/app/mcRegistry/ffffffff000000000000000000000019.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffff000000000000000000000021.tlbin:system/app/mcRegistry/ffffffff000000000000000000000021.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffff000000000000000000000041.tlbin:system/app/mcRegistry/ffffffff000000000000000000000041.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
    vendor/samsung/gts2-common/proprietary/app/mcRegistry/fffffffff0000000000000000000001e.tlbin:system/app/mcRegistry/fffffffff0000000000000000000001e.tlbin